{{- if eq (include "cheshmhayash-chart.hasManagedAuth" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cheshmhayash-chart.secretName" . }}
  labels:
    {{- include "cheshmhayash-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $i, $c := .Values.clusters }}
  {{- if and $c.auth $c.auth.userPassword }}
  {{ $c.name }}-user: {{ $c.auth.userPassword.user | quote }}
  {{ $c.name }}-password: {{ $c.auth.userPassword.password | quote }}
  {{- end }}
  {{- end }}
{{- end }}
