apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cheshmhayash.configMapName" . }}
  labels:
    {{- include "cheshmhayash.labels" . | nindent 4 }}
data:
  settings.toml: |
    {{- include "cheshmhayash.settingsToml" . | nindent 4 }}
